type: object
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier representing a specific product
  title:
    type: string
    description: Product name
  description:
    type: string
    description: Product description
  price:
    type: number
    format: double
    description: Product price
  cost:
    type: number
    format: double
    description: Product price
  # tags:
  #   type: array
  #   items:
  #     type: string
  #   description: Product tags
  categories:
    type: array
    description: Product categories
    items:
      type: string
  dimensions:
    type: object
    description: Product dimensions
    properties:
      length:
        type: number
        format: double
        description: Product length
      width:
        type: number
        format: double
        description: Product width
      height:
        type: number
        format: double
        description: Product height
  # status:
  #   type: string
  #   description: Product status
  # inventory:
  #   type: integer
  #   format: int32
  #   description: Product inventory
  images:
    type: array
    items:
      type: string
    description: Product images
  # reviews:
  #   type: array
  #   items:
  #     $ref: review.yaml
  # relatedProducts:
  #   type: array
  #   items:
  #     $ref: product.yaml
  createdAt:
    type: string
    format: date-time
    description: Product creation date
  updatedAt:
    type: string
    format: date-time
    description: Product last update date
