type: object
properties:
  id:
    type: string
    format: uuid
    description: Unique identifier representing a specific product
    example: 123e4567-e89b-12d3-a456-426614174000
  title:
    type: string
    description: Product name
    example: "Product Name"
  description:
    type: string
    description: Product description
    example: "Product description"
  price:
    type: number
    format: double
    description: Product price
    example: 9.99
  cost:
    type: number
    format: double
    description: Product price
    example: 5.99
  # tags:
  #   type: array
  #   items:
  #     type: string
  #   description: Product tags
  categories:
    type: array
    description: Product categories
    items:
      type: string
    example: ["Category 1", "Category 2"]
  dimensions:
    type: object
    description: Product dimensions
    properties:
      length:
        type: number
        format: double
        description: Product length
        example: 10
      width:
        type: number
        format: double
        description: Product width
        example: 5
      height:
        type: number
        format: double
        description: Product height
        example: 2
    example:
      length: 10
      width: 5
      height: 2
  # status:
  #   type: string
  #   description: Product status
  # inventory:
  #   type: integer
  #   format: int32
  #   description: Product inventory
  images:
    type: array
    items:
      type: string
    description: Product images
    example: ["image1.jpg", "image2.jpg"]
  # reviews:
  #   type: array
  #   items:
  #     $ref: review.yaml
  # relatedProducts:
  #   type: array
  #   items:
  #     $ref: product.yaml
  createdAt:
    type: string
    format: date-time
    description: Product creation date
    example: "2021-01-01T00:00:00Z"
  updatedAt:
    type: string
    format: date-time
    description: Product last update date
    example: "2021-01-01T00:00:00Z"
