get:
  tags:
    - Product
  summary: List all products
  description: |
    List all products.
  operationId: listProducts
  responses:
    "200":
      description: A list of products
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../components/schemas/v1/product.yaml"
    "401":
      description: Unauthorized
    "403":
      description: Forbidden
    "404":
      description: Not Found
    "500":
      description: Internal Server Error
